AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Aws-Concepts-Backend-Infrastructure

Parameters:
  environmentName:
    Type: String
    Default: Prod
  certificateArnName:
    Type: String
    Default: arn:aws:acm:us-east-1:639658585076:certificate/6fc81c16-b064-43aa-bc79-5b8d56f65fcd
  lambdaCodeUriKey:
    Type: String
  lambdaCodeUriBucket:
    Type: String
Resources:
  
  apiGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Description: awsconcepts API Gateway
      ProtocolType: HTTP
      DisableExecuteApiEndpoint: false
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - GET
          - HEAD
          - OPTIONS
          - POST
          - PUT
          - DELETE
          - PATCH
      Name: !Sub "${environmentName}-api-gtw" 

  apiGatewayStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref apiGateway
      StageName: "$default"
      Description: Live Stage
      AutoDeploy: true 

  apiGatewayV2Route:
    Type: "AWS::ApiGatewayV2::Route"
    Properties:
        ApiId: !Ref apiGateway
        ApiKeyRequired: false
        AuthorizationType: "NONE"
        RouteKey: "ANY /{proxy+}"
        Target: !Sub "integrations/${apiGatewayLambdaIntegration}"

  apiGatewayLambdaIntegration:
    Type: "AWS::ApiGatewayV2::Integration"
    Properties:
        ApiId: !Ref apiGateway
        ConnectionType: "INTERNET"
        IntegrationMethod: "POST"
        IntegrationType: "AWS_PROXY"
        IntegrationUri: !GetAtt lambdaFunction.Arn
        TimeoutInMillis: 30000
        PayloadFormatVersion: "2.0"

  apiDomainName1:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: awsconcepts.com
      DomainNameConfigurations:
        - EndpointType: REGIONAL
          CertificateArn: !Ref certificateArnName
 
  apiDomainName2:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: www.awsconcepts.com
      DomainNameConfigurations:
        - EndpointType: REGIONAL
          CertificateArn: !Ref certificateArnName
 
  apiDomainName3:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: api.awsconcepts.com
      DomainNameConfigurations:
        - EndpointType: REGIONAL
          CertificateArn: !Ref certificateArnName

  route53RecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Name: "api.awsconcepts.com."
      Type: "A"
      AliasTarget: 
        HostedZoneId: !GetAtt apiDomainName3.DistributionHostedZoneId
        DNSName: !GetAtt apiDomainName3.DistributionDomainName
        EvaluateTargetHealth: true
      HostedZoneId: "Z0127351KJ3CF358L0CT"

  apiBasePathMapping1:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      DomainName: !Ref apiDomainName1
      ApiId: !Ref apiGateway
      Stage: !Ref apiGatewayStage

  apiBasePathMapping2:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      DomainName: !Ref apiDomainName2
      ApiId: !Ref apiGateway
      Stage: !Ref apiGatewayStage

  lambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: 
        S3Bucket: !Ref lambdaCodeUriBucket
        S3Key: !Sub "${lambdaCodeUriKey}/rootlambdapackage.zip"
        
      Description: Root Lambda function
      FunctionName: !Sub "${environmentName}-root-lambda"
      Handler: AwsConceptsRootLambda
      Architectures:
        - x86_64
      MemorySize: 256
      Role: !GetAtt lambdaIAMRole.Arn
      Runtime: dotnet6
      Timeout: 30
      TracingConfig:
        Mode: "Active"

  lambdaApiGatewayInvoke:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt lambdaFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${apiGateway}/*/*/{proxy+}

  lambdaFunctionStreamProcessor:
    Type: AWS::Lambda::Function
    Properties:
      Code: 
        S3Bucket: !Ref lambdaCodeUriBucket
        S3Key: !Sub "${lambdaCodeUriKey}/datastreamprocessor.zip"
      Description: Root Lambda function
      FunctionName: !Sub "${environmentName}-data-stream-processor"
      Handler: DataStreamProcessor::DataStreamProcessor.Function::FunctionHandler
      Architectures:
        - x86_64
      MemorySize: 256
      Role: !GetAtt lambdaIAMRole.Arn
      Runtime: dotnet6
      Timeout: 30
      TracingConfig:
        Mode: "Active"

  lambdaEventSourceMapping:
    Type: "AWS::Lambda::EventSourceMapping"
    Properties:
      BatchSize: 1
      EventSourceArn: !GetAtt dynamoDBTable.StreamArn
      FunctionName: !GetAtt lambdaFunctionStreamProcessor.Arn
      Enabled: true
      MaximumBatchingWindowInSeconds: 0
      ParallelizationFactor: 1
      MaximumRecordAgeInSeconds: -1
      BisectBatchOnFunctionError: false
      MaximumRetryAttempts: -1
      TumblingWindowInSeconds: 0

  lambdaIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${environmentName}-root-lambda:*
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${environmentName}-data-stream-processor:*
              - Action:
                  - dynamodb:PutItem
                  - dynamodb:BatchGet*
                  - dynamodb:DescribeStream
                  - dynamodb:ListStreams
                  - dynamodb:DescribeTable
                  - dynamodb:Get*
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:BatchWrite*
                  - dynamodb:CreateTable
                  - dynamodb:Delete*
                  - dynamodb:Update*
                  - dynamodb:PutItem
                  - dynamodb:GetShardIterator
                Resource: "*"
                Effect: Allow
              - Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetObject
                  - s3:GetObjectAcl
                  - s3:AbortMultipartUpload
                  - s3:PutObjectAcl
                  - s3:GetObject
                  - s3:GetObjectAcl
                  - s3:AbortMultipartUpload
                Resource: !GetAtt
                  - s3Bucket
                  - Arn
                Effect: Allow
          PolicyName: lambdaIAM

  lambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${environmentName}-root-lambda
      RetentionInDays: 30

  dynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions: 
        - 
          AttributeName: "pk"
          AttributeType: "S"
        - 
          AttributeName: "sk"
          AttributeType: "S"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "awsconcepts"
      KeySchema: 
        - 
          AttributeName: "pk"
          KeyType: "HASH"
        - 
          AttributeName: "sk"
          KeyType: "RANGE"  
      GlobalSecondaryIndexes: 
        - 
          IndexName: "sk-pk-index"
          KeySchema: 
            - 
              AttributeName: "sk"
              KeyType: "HASH"
            - 
              AttributeName: "pk"
              KeyType: "RANGE"
          Projection: 
              ProjectionType: "ALL"
          ProvisionedThroughput: 
              ReadCapacityUnits: 0
              WriteCapacityUnits: 0
      KinesisStreamSpecification:
          StreamArn: !GetAtt kinesisStream.Arn
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  s3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "awsconcepts"
      VersioningConfiguration: 
          Status: "Enabled"
  
  kinesisStream:
    Type: "AWS::Kinesis::Stream"
    Properties:
      Name: "awsconcepts"
      RetentionPeriodHours: 24
      ShardCount: 1

Outputs:
  apiGatewayInvokeURL:
    Value: !Sub https://${apiGateway}.execute-api.${AWS::Region}.amazonaws.com/api

  lambdaArn:
    Value: !GetAtt lambdaFunction.Arn